root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ./cmd/app/main.go"
delay = 1000  # Задержка перед пересборкой
exclude_dir = ["assets", "tmp", "vendor", ".git", "node_modules"]
include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "toml", "env"]
include_dir = ["cmd", "internal", "pkg", "api"]  # Явно указываем директории для наблюдения

# Параметры для пересборки
stop_on_error = false
send_interrupt = true
kill_delay = "500ms"

[log]
time = true
level = "debug"  # Включаем детальное логирование

[misc]
clean_on_exit = true