services:
  app:
    container_name: shop-auth
    build:
      dockerfile: Dockerfile
      context: .
    expose:
      - 3000
    environment:
      DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@shop_db:${DB_PORT}/${DB_NAME}?sslmode=disable
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./:/app
    #    depends_on:
    #      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
    networks:
      app-network:
      shop-network:

networks:
  app-network:
    driver: bridge
  shop-network:
    external: true
volumes:
  postgres_data:
  redis_data:
